src/GPS/UserBundle/Entity/User.php
<?php

namespace GPS\UserBundle\Entity;

use FOS\UserBundle\Entity\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class User extends BaseUser
{
    const ROLE_ADMIN    = 'ROLE_ADMIN';
    const ROLE_USER     = 'ROLE_USER';

    public static $ROLES = array(
        self::ROLE_ADMIN    => 'Administrador',
        self::ROLE_USER     => 'Usuario'
    );


    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="ruc", type="string", length=15)
     */
    protected $ruc = "0";

    /**
     * @var string
     *
     * @ORM\Column(name="phones", type="string", length=255)
     */
    protected $phones = "0";

    /**
     * @var array
     *
     * @ORM\Column(name="options", type="array")
     */
    protected $options = array();

    /**
     * @ORM\ManyToMany(targetEntity="GPS\UserBundle\Entity\Group")
     * @ORM\JoinTable(name="fos_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set ruc
     *
     * @param string $ruc
     * @return User
     */
    public function setRuc($ruc)
    {
        $this->ruc = $ruc;

        return $this;
    }

    /**
     * Get ruc
     *
     * @return string
     */
    public function getRuc()
    {
        return $this->ruc;
    }

    /**
     * Set phones
     *
     * @param string $phones
     * @return User
     */
    public function setPhones($phones)
    {
        $this->phones = $phones;

        return $this;
    }

    /**
     * Get phones
     *
     * @return string
     */
    public function getPhones()
    {
        return $this->phones;
    }

    /**
     * Set options
     *
     * @param array $options
     * @return User
     */
    public function setOptions($options)
    {
        $this->options = $options;

        return $this;
    }

    /**
     * Get options
     *
     * @return array
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function getRoleNames()
    {
        $roles = array();

        foreach ($this->getRoles() as $role) {
            $roles[] = str_replace('_', ' ', substr($role, 5));
        }

        return $roles;
    }
}

src/GPS/UserBundle/Form/UserType.php
<?php

namespace GPS\UserBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseType;
use GPS\UserBundle\Entity\User;

class UserType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('enabled')
            ->add('roles')
            ->add('ruc')
            ->add('phones')
            ->add('groups')
            ->add('options');
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'GPS\UserBundle\Entity\User'
        ));
    }

    public function getName()
    {
        return 'gps_userbundle_usertype';
    }
}

src/GPS/UserBundle/Controller/UserController.php
<?php

namespace GPS\UserBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use GPS\UserBundle\Entity\User;
use GPS\UserBundle\Form\UserType;

/**
 * User controller.
 *
 * @Route("/user")
 */
class UserController extends Controller
{
    /**
     * Lists all User entities.
     *
     * @Route("/", name="user")
     * @Template()
     */
    public function indexAction()
    {
        $userManager = $this->get('fos_user.user_manager');
        $users = $userManager->findUsers();

        return array(
            'users' => $users,
        );
    }

    /**
     * Finds and displays a User
     *
     * @Route("/{username}/show", name="user_show")
     * @Template()
     */
    public function showAction($username)
    {
        $userManager = $this->get('fos_user.user_manager');
        $user = $userManager->findUserByUsername($username);

        if (!$user) {
            throw $this->createNotFoundException('Unable to find User');
        }

        return array(
            'user'      => $user,
        );
    }

    /**
     * Displays a form to create a new User
     *
     * @Route("/new", name="user_new")
     * @Template()
     */
    public function newAction()
    {
        $user = new User();
        $form   = $this->createForm(new UserType(get_class($user)), $user);

        return array(
            'user' => $user,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a new User
     *
     * @Route("/create", name="user_create")
     * @Method("POST")
     * @Template("GPSUserBundle:User:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $user  = new User();
        $form = $this->createForm(new UserType(get_class($user)), $user);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirect($this->generateUrl('user'));
        }

        return array(
            'user' => $user,
            'form'   => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing User
     *
     * @Route("/{id}/edit", name="user_edit")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $user = $em->getRepository('GPSUserBundle:User')->find($id);

        if (!$user) {
            throw $this->createNotFoundException('Unable to find User');
        }

        $form = $this->createForm(new UserType(get_class($user)), $user);

        return array(
            'user'      => $user,
            'form'   => $form->createView(),
        );
    }

    /**
     * Edits an existing User
     *
     * @Route("/{id}/update", name="user_update")
     * @Method("POST")
     * @Template("GPSUserBundle:User:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $user = $em->getRepository('GPSUserBundle:User')->find($id);

        if (!$user) {
            throw $this->createNotFoundException('Unable to find User');
        }

        $form = $this->createForm(new UserType(get_class($user)), $user);
        $form->bind($request);

        if ($form->isValid()) {
            $em->persist($user);
            $em->flush();

            return $this->redirect($this->generateUrl('user'));
        }

        return array(
            'user'      => $user,
            'form'   => $form->createView(),
        );
    }

    /**
     * Enable/Disable User
     *
     * @Route("/{username}/activate", name="user_activate")
     */
    public function activateAction(Request $request, $username)
    {
        /** @var $userManager \FOS\UserBundle\Entity\UserManager */
        $userManager = $this->get('fos_user.user_manager');

        /** @var $user User */
        $user = $userManager->findUserByUsername($username);

        if (!$user) {
            throw new \InvalidArgumentException(sprintf('User identified by "%s" username does not exist.', $username));
        }
        $user->setEnabled(!$user->isEnabled());
        $userManager->updateUser($user);

        return $this->redirect($this->generateUrl('user'));
    }
}

src/GPS/UserBundle/Resources/views/User/edit.html.twig
{% extends 'GPSUserBundle::layout.html.twig' %}

{% block gps_user_content %}

    <h1>User edit</h1>

    <form action="{{ path('user_update', { 'id': user.id }) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
        <p>
            <button type="submit">Edit</button>
        </p>
    </form>

    <ul class="record_actions">
        <li>
            <a href="{{ path('user') }}">
                Back to the list
            </a>
        </li>
    </ul>

{% endblock gps_user_content %}

src/GPS/UserBundle/Resources/views/User/index.html.twig
{% extends 'GPSUserBundle::layout.html.twig' %}

{% block gps_user_content %}

    <h2>
        Usuarios
        <a class="btn btn-small btn-primary" href="{{ path('user_new') }}">
            <i class="icon-plus icon-white"></i> Nuevo Usuario
        </a>
    </h2>

    <table class="table table-full">
        <thead>
        <tr>
            <th class="span2">Usuario</th>
            <th class="span3">Email</th>
            <th class="span2">Último Ingreso</th>
            <th class="span3">Permisos</th>
            <th class="span2">Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>
                    <a href="{{ path('user_show', { 'username': user.username }) }}">{{ user.username }}</a>
                </td>
                <td>{{ user.email }}</td>
                <td>{% if user.lastLogin %}{{ user.lastLogin|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>
                    {% for role in user.roleNames %}
                        <span class="badge badge-info">{{ role }}</span>
                    {% endfor %}
                </td>
                <td>
                    {% if user.enabled %}
                        <a class="btn btn-mini btn-success"
                           href="{{ path('user_activate', { 'username': user.username }) }}">
                            <i class="icon-ok icon-white"></i> Activo
                        </a>
                    {% else %}
                        <a class="btn btn-mini btn-danger"
                           href="{{ path('user_activate', { 'username': user.username }) }}">
                            <i class="icon-remove icon-white"></i> Inactivo
                        </a>
                    {% endif %}
                    <a class="btn btn-mini" href="{{ path('user_edit', { 'id': user.id }) }}">
                        <i class="icon-pencil"></i> Editar
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock gps_user_content %}

src/GPS/UserBundle/Resources/views/User/new.html.twig
{% extends 'GPSUserBundle::layout.html.twig' %}

{% block gps_user_content %}

    <h1>Nuevo Usuario</h1>

    <form action="{{ path('user_create') }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
        <p>
            <button type="submit">Create</button>
        </p>
    </form>

    <ul class="record_actions">
        <li>
            <a href="{{ path('user') }}">
                Back to the list
            </a>
        </li>
    </ul>


{% endblock gps_user_content %}

src/GPS/UserBundle/Resources/views/User/show.html.twig
{% extends 'GPSUserBundle::layout.html.twig' %}

{% block gps_user_content %}

    <h1>User</h1>

    <table class="record_properties">
        <tbody>
        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Enabled</th>
            <td>{{ user.enabled }}</td>
        </tr>
        <tr>
            <th>Lastlogin</th>
            <td>{{ user.lastLogin|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Roles</th>
            <td>{{ user.roles|join(', ') }}</td>
        </tr>
        <tr>
            <th>Ruc</th>
            <td>{{ user.ruc }}</td>
        </tr>
        <tr>
            <th>Phones</th>
            <td>{{ user.phones }}</td>
        </tr>
        <tr>
            <th>Options</th>
            <td>{{ user.options|join(', ') }}</td>
        </tr>
        </tbody>
    </table>

    <ul class="record_actions">
        <li>
            <a href="{{ path('user') }}">
                Back to the list
            </a>
        </li>
        <li>
            <a href="{{ path('user_edit', { 'id': user.id }) }}">
                Edit
            </a>
        </li>
    </ul>

{% endblock gps_user_content %}