src/GPS/GPSBundle/Entity/Vehicle.php
<?php

namespace GPS\GPSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use GPS\GPSBundle\Model\AbstractPhoto;
use GPS\UserBundle\Entity\Group;

/**
 * Vehicle
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="GPS\GPSBundle\Entity\VehicleRepository")
 */
class Vehicle extends AbstractPhoto
{
    /**
     * @var string
     *
     * @ORM\Column(name="id", type="string", length=255)
     * @ORM\Id
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="plate", type="string", length=20)
     */
    private $plate;

    /**
     * @var string
     *
     * @ORM\ManyToOne(targetEntity="Driver", inversedBy="vehicles")
     * @ORM\JoinColumn(name="driver_id", referencedColumnName="id")
     */
    private $driver;

    /**
     * @var string
     *
     * @ORM\Column(name="brand", type="string", length=50)
     */
    private $brand;

    /**
     * @var string
     *
     * @ORM\Column(name="model", type="string", length=20)
     */
    private $model;

    /**
     * @var integer
     *
     * @ORM\Column(name="year", type="integer")
     */
    private $year;

    /**
     * @var string
     *
     * @ORM\Column(name="color", type="string", length=20)
     */
    private $color;

    /**
     * @var string
     *
     * @ORM\Column(name="insurance", type="string", length=50)
     */
    private $insurance;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="insuranceStart_at", type="date")
     */
    private $insuranceStart_at;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="insuranceEnd_at", type="date")
     */
    private $insuranceEnd_at;

    /**
     * @var string
     *
     * @ORM\Column(name="insuranceCompany", type="string", length=50)
     */
    private $insuranceCompany;

    /**
     * @var string
     *
     * @ORM\Column(name="chip", type="string", length=50)
     */
    private $chip;

    /**
     * @ORM\OneToMany(targetEntity="Plot", mappedBy="trackId")
     */
    private $plots;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="installation_at", type="date")
     */
    private $installation_at;

    /**
     * @var string
     *
     * @ORM\Column(name="trackerModel", type="string", length=20)
     */
    private $trackerModel;

    /**
     * @var string
     *
     * @ORM\Column(name="trackerBrand", type="string", length=20)
     */
    private $trackerBrand;

    /**
     * @var Group
     *
     * @ORM\ManyToOne(targetEntity="GPS\UserBundle\Entity\Group", inversedBy="vehicles")
     */
    private $group;

    /**
     * @var boolean
     *
     * @ORM\Column(name="status", type="boolean")
     */
    private $status;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * Set plate
     *
     * @param string $plate
     * @return Vehicle
     */
    public function setPlate($plate)
    {
        $this->plate = $plate;
    
        return $this;
    }

    /**
     * Get plate
     *
     * @return string 
     */
    public function getPlate()
    {
        return $this->plate;
    }

    /**
     * Set driver
     *
     * @param string $driver
     * @return Vehicle
     */
    public function setDriver($driver)
    {
        $this->driver = $driver;
    
        return $this;
    }

    /**
     * Get driver
     *
     * @return string 
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Set brand
     *
     * @param string $brand
     * @return Vehicle
     */
    public function setBrand($brand)
    {
        $this->brand = $brand;
    
        return $this;
    }

    /**
     * Get brand
     *
     * @return string 
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * Set model
     *
     * @param string $model
     * @return Vehicle
     */
    public function setModel($model)
    {
        $this->model = $model;
    
        return $this;
    }

    /**
     * Get model
     *
     * @return string 
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Set year
     *
     * @param integer $year
     * @return Vehicle
     */
    public function setYear($year)
    {
        $this->year = $year;
    
        return $this;
    }

    /**
     * Get year
     *
     * @return integer 
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Set color
     *
     * @param string $color
     * @return Vehicle
     */
    public function setColor($color)
    {
        $this->color = $color;
    
        return $this;
    }

    /**
     * Get color
     *
     * @return string 
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Set insurance
     *
     * @param string $insurance
     * @return Vehicle
     */
    public function setInsurance($insurance)
    {
        $this->insurance = $insurance;
    
        return $this;
    }

    /**
     * Get insurance
     *
     * @return string 
     */
    public function getInsurance()
    {
        return $this->insurance;
    }

    /**
     * Set insuranceStart_at
     *
     * @param \DateTime $insuranceStartAt
     * @return Vehicle
     */
    public function setInsuranceStartAt($insuranceStartAt)
    {
        $this->insuranceStart_at = $insuranceStartAt;
    
        return $this;
    }

    /**
     * Get insuranceStart_at
     *
     * @return \DateTime 
     */
    public function getInsuranceStartAt()
    {
        return $this->insuranceStart_at;
    }

    /**
     * Set insuranceEnd_at
     *
     * @param \DateTime $insuranceEndAt
     * @return Vehicle
     */
    public function setInsuranceEndAt($insuranceEndAt)
    {
        $this->insuranceEnd_at = $insuranceEndAt;
    
        return $this;
    }

    /**
     * Get insuranceEnd_at
     *
     * @return \DateTime 
     */
    public function getInsuranceEndAt()
    {
        return $this->insuranceEnd_at;
    }

    /**
     * Set insuranceCompany
     *
     * @param string $insuranceCompany
     * @return Vehicle
     */
    public function setInsuranceCompany($insuranceCompany)
    {
        $this->insuranceCompany = $insuranceCompany;
    
        return $this;
    }

    /**
     * Get insuranceCompany
     *
     * @return string 
     */
    public function getInsuranceCompany()
    {
        return $this->insuranceCompany;
    }

    /**
     * Set chip
     *
     * @param string $chip
     * @return Vehicle
     */
    public function setChip($chip)
    {
        $this->chip = $chip;
    
        return $this;
    }

    /**
     * Get chip
     *
     * @return string 
     */
    public function getChip()
    {
        return $this->chip;
    }

    /**
     * @param mixed $plots
     */
    public function setPlots($plots)
    {
        $this->plots = $plots;
    }

    /**
     * @return mixed
     */
    public function getPlots()
    {
        return $this->plots;
    }


    /**
     * Set installation_at
     *
     * @param \DateTime $installationAt
     * @return Vehicle
     */
    public function setInstallationAt($installationAt)
    {
        $this->installation_at = $installationAt;
    
        return $this;
    }

    /**
     * Get installation_at
     *
     * @return \DateTime 
     */
    public function getInstallationAt()
    {
        return $this->installation_at;
    }

    /**
     * @param string $trackerBrand
     */
    public function setTrackerBrand($trackerBrand)
    {
        $this->trackerBrand = $trackerBrand;
    }

    /**
     * @return string
     */
    public function getTrackerBrand()
    {
        return $this->trackerBrand;
    }

    /**
     * @param string $trackerModel
     */
    public function setTrackerModel($trackerModel)
    {
        $this->trackerModel = $trackerModel;
    }

    /**
     * @return string
     */
    public function getTrackerModel()
    {
        return $this->trackerModel;
    }

    protected function getUploadDir()
    {
        return 'uploads/vehicle';
    }

    /**
     * @param \GPS\GPSBundle\Entity\boolena $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @param \GPS\UserBundle\Entity\Group $group
     */
    public function setGroup($group)
    {
        $this->group = $group;
    }

    /**
     * @return \GPS\UserBundle\Entity\Group
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * @return \GPS\GPSBundle\Entity\boolena
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function isEnabled()
    {
        return $this->getStatus();
    }


}

src/GPS/GPSBundle/Form/VehicleType.php
<?php

namespace GPS\GPSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class VehicleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('plate', 'text', array(
                'label' => 'Placa: ',
            ))
            ->add('driver', 'entity', array(
                'label' => 'Conductor: ',
                'class' => 'GPSBundle:Driver'
            ))
            ->add('brand', 'text', array(
                'label' => 'Marca: ',
            ))
            ->add('model', 'text', array(
                'label' => 'Modelo: ',
            ))
            ->add('year', 'number', array(
                'label' => 'Año: ',
            ))
            ->add('color', 'text', array(
                'label' => 'Color: ',
            ))
            ->add('insurance', 'text', array(
                'label' => 'Numero de seguro: ',
            ))
            ->add('insuranceStart_at', 'date', array(
                'label' => 'Fecha de inicio del seguro: ',
            ))
            ->add('insuranceEnd_at', 'date', array(
                'label' => 'Fecha de fin del seguro: ',
            ))
            ->add('insuranceCompany', 'text', array(
                'label' => 'Compañia de seguros: ',
            ))
            ->add('chip', 'text', array(
                'label' => 'Numero del chip: ',
            ))
            ->add('id', 'text', array(
                'label' => 'Id del GPS: ',
            ))
            ->add('installation_at', 'date', array(
                'label' => 'Fecha de instalación: ',
            ))
            ->add('trackerModel', 'text', array(
                'label' => 'Modelo del rastreador: ',
            ))
            ->add('trackerBrand', 'text', array(
                'label' => 'Marca del rastreador: ',
            ))
            ->add('group')
            ->add('file', 'file', array(
                'label' => 'Foto: ',
                'required' => false,
            ))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'GPS\GPSBundle\Entity\Vehicle'
        ));
    }

    public function getName()
    {
        return 'gps_gpsbundle_vehicletype';
    }
}

src/GPS/GPSBundle/Controller/VehicleController.php
<?php

namespace GPS\GPSBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use GPS\GPSBundle\Entity\Vehicle;
use GPS\GPSBundle\Form\VehicleType;

/**
 * Vehicle controller.
 *
 * @Route("/vehicle")
 */
class VehicleController extends Controller
{
    /**
     * Lists all Vehicle entities.
     *
     * @Route("/", name="vehicle")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('GPSBundle:Vehicle')->findAll();

        return array(
            'entities' => $entities,
        );
    }

    /**
     * Finds and displays a Vehicle entity.
     *
     * @Route("/{id}/show", name="vehicle_show")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GPSBundle:Vehicle')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Vehicle entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to create a new Vehicle entity.
     *
     * @Route("/new", name="vehicle_new")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Vehicle();
        $form   = $this->createForm(new VehicleType(), $entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a new Vehicle entity.
     *
     * @Route("/create", name="vehicle_create")
     * @Method("POST")
     * @Template("GPSBundle:Vehicle:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity  = new Vehicle();
        $form = $this->createForm(new VehicleType(), $entity);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $entity->setStatus(0);
            $entity->upload();

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('vehicle_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Vehicle entity.
     *
     * @Route("/{id}/edit", name="vehicle_edit")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GPSBundle:Vehicle')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Vehicle entity.');
        }

        $editForm = $this->createForm(new VehicleType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Edits an existing Vehicle entity.
     *
     * @Route("/{id}/update", name="vehicle_update")
     * @Method("POST")
     * @Template("GPSBundle:Vehicle:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GPSBundle:Vehicle')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Vehicle entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new VehicleType(), $entity);
        $editForm->bind($request);

        if ($editForm->isValid()) {

            $entity->upload();

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('vehicle_edit', array('id' => $entity->getId())));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Vehicle entity.
     *
     * @Route("/{id}/delete", name="vehicle_delete")
     * @Method("POST")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('GPSBundle:Vehicle')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Vehicle entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('vehicle'));
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }

    /**                                                       activat
     * Vehicle activate and disabled
     *
     * @Route("/{id}/activate", name="vehicle_activate")
     */
    public function activateAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GPSBundle:Vehicle')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Vehicle entity.');
        }

        $entity->setStatus(!$entity->isEnabled());

        $em->persist($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('vehicle'));
    }
}

src/GPS/GPSBundle/Resources/views/Vehicle/edit.html.twig
{% extends 'GPSBundle::layout.html.twig' %}

{% block content %}

<h1>Editar Vehículo</h1>

<form action="{{ path('vehicle_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
    {{ form_widget(edit_form) }}
    <p>
        <button type="submit">Editar</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('vehicle') }}">
            Volver a la lista de vehículos
        </a>
    </li>
    <li>
        <form action="{{ path('vehicle_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Eliminar</button>
        </form>
    </li>
</ul>

{% endblock content %}

src/GPS/GPSBundle/Resources/views/Vehicle/index.html.twig
{% extends 'GPSBundle::layout.html.twig' %}

{% block content %}

<h2>
    Vehículos
    <a class="btn btn-small btn-primary" href="{{ path('vehicle_new') }}">
        <i class="icon-plus icon-white"></i> Nuevo Vehículo
    </a>
</h2>

<table class="table table-full">
    <thead>
        <tr>
            <th>Placa</th>
            <th>Conductor</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Año</th>
            <th>GPS ID</th>
            <th>Acciónes</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        <tr>
            <td class="span2"><a href="{{ path('vehicle_show', { 'id': entity.id }) }}">{{ entity.plate }}<a/></td>
            <td>{{ entity.driver }}</td>
            <td>{{ entity.brand }}</td>
            <td>{{ entity.model }}</td>
            <td>{{ entity.year }}</td>
            <td>{{ entity.id }}</td>
            <td>
                {% if entity.enabled %}
                    <a class="btn btn-mini btn-success"
                       href="{{ path('vehicle_activate', { 'id': entity.id }) }}">
                        <i class="icon-ok icon-white"></i> Activo
                    </a>
                {% else %}
                    <a class="btn btn-mini btn-danger"
                       href="{{ path('vehicle_activate', { 'id': entity.id }) }}">
                        <i class="icon-remove icon-white"></i> Inactivo
                    </a>
                {% endif %}
                <a class="btn btn-mini" href="{{ path('vehicle_edit', { 'id': entity.id }) }}">
                    <i class="icon-pencil"></i> Editar
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

src/GPS/GPSBundle/Resources/views/Vehicle/new.html.twig
{% extends 'GPSBundle::layout.html.twig' %}

{% block content %}

<h1>Agregar vehículo</h1>

<form action="{{ path('vehicle_create') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <p>
        <button type="submit">Crear</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('vehicle') }}">
            Volver a la lista de vehículos.
        </a>
    </li>
</ul>

{% endblock content %}

src/GPS/GPSBundle/Resources/views/Vehicle/show.html.twig
{% extends 'GPSBundle::layout.html.twig' %}

{% block content %}

<h1>Vehicle</h1>

<table class="table table-full">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Placa</th>
            <td>{{ entity.plate }}</td>
        </tr>
        <tr>
            <th>Conductor</th>
            <td>{{ entity.driver }}</td>
        </tr>
        <tr>
            <th>Marca</th>
            <td>{{ entity.brand }}</td>
        </tr>
        <tr>
            <th>Modelo</th>
            <td>{{ entity.model }}</td>
        </tr>
        <tr>
            <th>Año</th>
            <td>{{ entity.year }}</td>
        </tr>
        <tr>
            <th>Color</th>
            <td>{{ entity.color }}</td>
        </tr>
        <tr>
            <th>Numero de seguro</th>
            <td>{{ entity.insurance }}</td>
        </tr>
        <tr>
            <th>Fecha de inicio del seguro</th>
            <td>{{ entity.insuranceStartat|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Fecha de fin del seguro</th>
            <td>{{ entity.insuranceEndat|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Compañia de seguros</th>
            <td>{{ entity.insuranceCompany }}</td>
        </tr>
        <tr>
            <th>Numero de Chip</th>
            <td>{{ entity.chip }}</td>
        </tr>
        <tr>
            <th>GPS ID</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Fecha de instalación.</th>
            <td>{{ entity.installationat|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Modelo de rastreador</th>
            <td>{{ entity.trackerModel }}</td>
        </tr>
        <tr>
            <th>Marca del rastreador</th>
            <td>{{ entity.trackerBrand }}</td>
        </tr>
        <tr>
            <th>Foto</th>
            <td>{{ entity.path }}</td>
        </tr>
    </tbody>
</table>

<ul class="record_actions">
    <li>
        <a href="{{ path('vehicle') }}">
            Volver a la lista de vehículos.
        </a>
    </li>
    <li>
        <a href="{{ path('vehicle_edit', { 'id': entity.id }) }}">
            Editar
        </a>
    </li>
    <li>
        <form action="{{ path('vehicle_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button class="btn btn-danger" type="submit">Eliminar</button>
        </form>
    </li>
</ul>

{% endblock content %}